version: '2'
services:
  nagios:
    image: wrix/nagiosbuild:latest
    ports:
      - 80:80
    environment:
      MAIL_APIKEY: "apikey"
      DEFAULT_MAILTO: "rasmusj@wrix.dk"
      DEFAULT_MAILFROM: "nagios@wrix.dk"
      CONTACT_MAIL: "rasmusj@wrix.dk"
      CONTACT_SMS: "rasmusjsms@wrix.dk"
    restart: always
